# Tensor Basics

In [2]:
import torch

In [3]:
import numpy as np

In [4]:
torch.__version__

'2.3.1+cu121'

In [5]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
arr.dtype

dtype('int64')

In [7]:
type(arr)

numpy.ndarray

In [8]:
x = torch.from_numpy(arr)

In [9]:
type(x)

torch.Tensor

In [10]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [11]:
x

tensor([1, 2, 3, 4, 5])

In [12]:
x.dtype

torch.int64

In [13]:
arr2d = np.arange(0.0,12.0)

In [14]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [15]:
arr2d = arr2d.reshape(4,3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [16]:
x2 = torch.from_numpy(arr2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [17]:
arr[0] = 99
arr

array([99,  2,  3,  4,  5])

In [18]:
my_arr = np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
my_tensor = torch.tensor(my_arr)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
my_other_tensor = torch.from_numpy(my_arr)
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
my_arr[0] = 9999
my_arr

array([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [22]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [23]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

This Python code uses the torch library (PyTorch) and numpy to demonstrate the conversion between NumPy arrays and PyTorch tensors.

* torch: PyTorch library for tensor computations, similar to NumPy but optimized for GPUs.
* numpy: Library for numerical computations in Python, with support for arrays.

This code demonstrates how PyTorch tensors can be created from NumPy arrays, the differences between creating a tensor using torch.tensor (which creates a copy) and torch.from_numpy (which shares memory), and how changes to the original NumPy array affect the tensor when memory is shared.

# Creating Tensors from Scratch

> NOTE: `tensor` and `Tensor` are two different things. `torch.tensor(new_arr)` will return *tensor([1, 2, 3], dtype=torch.int32)*. `torch.Tensor(new_arr)` will return the array in float. *tensor([1., 2., 3.])*.

In [24]:
torch.empty(4,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [25]:
torch.zeros(4,3,dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [26]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [27]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [28]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [29]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [30]:
my_tensor = torch.tensor([1,2,3])
my_tensor.dtype

torch.int64

In [31]:
my_tensor = my_tensor.type(torch.int32)
my_tensor.dtype

torch.int32

In [32]:
torch.rand(4,3)

tensor([[0.3595, 0.9648, 0.9850],
        [0.9959, 0.1424, 0.5132],
        [0.9827, 0.1299, 0.0922],
        [0.7837, 0.3270, 0.1701]])

In [33]:
torch.randn(4,3)

tensor([[-2.0055, -0.5605,  0.7052],
        [-0.2336, -2.3686,  1.9574],
        [ 0.9095,  0.7311,  1.0327],
        [ 1.5418, -0.0367,  2.8398]])

In [34]:
torch.randint(low=0,high=10,size=(5,5))

tensor([[6, 0, 2, 3, 2],
        [2, 2, 3, 3, 1],
        [4, 2, 7, 3, 9],
        [9, 8, 7, 0, 6],
        [3, 8, 8, 9, 6]])

In [35]:
x = torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [36]:
x.shape

torch.Size([2, 5])

In [37]:
torch.rand_like(x)

tensor([[0.3550, 0.7343, 0.3807, 0.5343, 0.7775],
        [0.9652, 0.8832, 0.7478, 0.5695, 0.3828]])

In [38]:
torch.randn_like(x)

tensor([[-0.1402, -0.6203,  0.1323, -1.2521,  1.2578],
        [-0.4273, -1.3504,  2.0570,  0.4173,  1.9928]])

In [39]:
torch.randint_like(x,low=0,high=10)

tensor([[3., 2., 5., 4., 9.],
        [9., 8., 9., 2., 7.]])

In [41]:
torch.randint_like(x,low=0,high=11)

tensor([[ 7.,  9.,  2.,  9.,  6.],
        [ 4.,  8.,  8., 10.,  1.]])

In [42]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [43]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [44]:
torch.rand(2,3)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])

# Tensor Operations

This section covers:

* Indexing and slicing
* Reshaping tensors (tensor views)
* Tensor arithmetic and basic operations
* Dot products
* Matrix multiplication
* Additional, more advanced operations


In [45]:
import torch
import numpy as np

## Indexing and slicing

Extracting specific values from a tensor works just the same as with NumPy arrays

![Diagram](http://www.scipy-lectures.org/_images/numpy_indexing.png)



In [46]:
x = torch.arange(6).reshape(3,2)
print(x)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [47]:
# Grabbing the right hand column values
x[:,1]

tensor([1, 3, 5])

In [48]:
# Grabbing the right hand column as a (3,1) slice
x[:,1:]

tensor([[1],
        [3],
        [5]])

## Reshape tensors with .view()

view() and reshape() do essentially the same thing by returning a reshaped tensor without changing the original tensor in place.


In [49]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [50]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [51]:
x.view(5,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [54]:
# x is unchanged
x

tensor([234,   1,   2,   3,   4,   5,   6,   7,   8,   9])

### Views reflect the most current data


In [53]:
z = x.view(2,5)
x[0]=234
print(z)

tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])


### Views can infer the correct size

By passing in -1 PyTorch will infer the correct value from the given tensor

In [55]:
x.view(2,-1)

tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [56]:
x.view(-1,5)

tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

### Adopt another tensor's shape with .view_as()

view_as(input) only works with tensors that have the same number of elements.


In [57]:
x.view_as(z)

tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

## Tensor Arithmetic

Adding tensors can be performed a few different ways depending on the desired result.

As a simple expression:

In [58]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

tensor([5., 7., 9.])


As arguments passed into a torch operation:


In [59]:
print(torch.add(a, b))

tensor([5., 7., 9.])


With an output tensor passed in as an argument:


In [60]:
result = torch.empty(3)
torch.add(a, b, out=result)  # equivalent to result=torch.add(a,b)
print(result)

tensor([5., 7., 9.])


Changing a tensor in-place

In [61]:
a.add_(b)  # equivalent to a=torch.add(a,b)
print(a)

tensor([5., 7., 9.])


# Basic Tensor Operations in PyTorch

## Arithmetic Operations

| OPERATION | FUNCTION   | DESCRIPTION               |
|-----------|------------|---------------------------|
| `a + b`   | `a.add(b)` | Element-wise addition      |
| `a - b`   | `a.sub(b)` | Subtraction                |
| `a * b`   | `a.mul(b)` | Multiplication             |
| `a / b`   | `a.div(b)` | Division                   |
| `a % b`   | `a.fmod(b)`| Modulo (remainder)         |
| `a^b`     | `a.pow(b)` | Power                      |

## Monomial Operations

| OPERATION       | FUNCTION            | DESCRIPTION                        |
|-----------------|---------------------|------------------------------------|
| `|a|`           | `torch.abs(a)`       | Absolute value                     |
| `1/a`           | `torch.reciprocal(a)`| Reciprocal                         |
| `√a`            | `torch.sqrt(a)`      | Square root                        |
| `log(a)`        | `torch.log(a)`       | Natural logarithm                  |
| `e^a`           | `torch.exp(a)`       | Exponential                        |
| `12.34 ==> 12.` | `torch.trunc(a)`     | Truncated integer                  |
| `12.34 ==> 0.34`| `torch.frac(a)`      | Fractional component               |

## Trigonometry

| OPERATION    | FUNCTION       | DESCRIPTION          |
|--------------|----------------|----------------------|
| `sin(a)`     | `torch.sin(a)` | Sine                 |
| `cos(a)`     | `torch.cos(a)` | Cosine               |
| `tan(a)`     | `torch.tan(a)` | Tangent              |
| `arcsin(a)`  | `torch.asin(a)`| Arc sine             |
| `arccos(a)`  | `torch.acos(a)`| Arc cosine           |
| `arctan(a)`  | `torch.atan(a)`| Arc tangent          |
| `sinh(a)`    | `torch.sinh(a)`| Hyperbolic sine      |
| `cosh(a)`    | `torch.cosh(a)`| Hyperbolic cosine    |
| `tanh(a)`    | `torch.tanh(a)`| Hyperbolic tangent   |

## Summary Statistics

| OPERATION      | FUNCTION        | DESCRIPTION                           |
|----------------|-----------------|---------------------------------------|
| `sum(a)`       | `torch.sum(a)`  | Sum                                   |
| `mean(a)`      | `torch.mean(a)` | Mean                                  |
| `amax(a)`      | `torch.max(a)`  | Maximum                               |
| `amin(a)`      | `torch.min(a)`  | Minimum                               |
| `torch.max(a, b)` | Returns a tensor of size `a` containing the element-wise max between `a` and `b`. |

> NOTE: Most arithmetic operations require float values. Those that do work with integers return integer tensors.
For example, torch.div(a,b) performs floor division (truncates the decimal) for integer types, and classic division for floats.

## Dot products

A dot product is the sum of the products of the corresponding entries of two 1D tensors. If the tensors are both vectors, the dot product is given as:

Dot products can be expressed as torch.dot(a,b) or a.dot(b) or b.dot(a)


In [62]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a.mul(b)) # for reference
print()
print(a.dot(b))

tensor([ 4., 10., 18.])

tensor(32.)


> NOTE: There's a slight difference between torch.dot() and numpy.dot(). While torch.dot() only accepts 1D arguments and returns a dot product, numpy.dot() also accepts 2D arguments and performs matrix multiplication. We show matrix multiplication below.

## Matrix multiplication

2D Matrix multiplication is possible when the number of columns in tensor A matches the number of rows in tensor B. In this case, the product of tensor A with size (x,y) and tensor B with size (y,z) results in a tensor of size (x,z).

Matrix multiplication can be computed using torch.mm(a,b) or a.mm(b) or a @ b.


In [63]:
a = torch.tensor([[0,2,4],[1,3,5]], dtype=torch.float)
b = torch.tensor([[6,7],[8,9],[10,11]], dtype=torch.float)

print('a: ',a.size())
print('b: ',b.size())
print('a x b: ',torch.mm(a,b).size())


a:  torch.Size([2, 3])
b:  torch.Size([3, 2])
a x b:  torch.Size([2, 2])


In [64]:
print(torch.mm(a,b))


tensor([[56., 62.],
        [80., 89.]])


In [65]:
print(a.mm(b))


tensor([[56., 62.],
        [80., 89.]])


In [66]:
print(a @ b)


tensor([[56., 62.],
        [80., 89.]])


## Matrix multiplication with broadcasting

Matrix multiplication that involves broadcasting can be computed using torch.matmul(a,b) or a.matmul(b) or a @ b

In [67]:
t1 = torch.randn(2, 3, 4)
t2 = torch.randn(4, 5)

print(torch.matmul(t1, t2).size())

torch.Size([2, 3, 5])


However, the same operation raises a RuntimeError with torch.mm():

In [68]:
print(torch.mm(t1, t2).size())


RuntimeError: self must be a matrix


## Advanced operations

### L2 or Euclidian Norm

When applied to a matrix, torch.norm() returns the Frobenius norm by default.


In [69]:
x = torch.tensor([2.,5.,8.,14.])
x.norm()


tensor(17.)

### Number of elements

Returns the number of elements in a tensor.

In [70]:
x = torch.ones(3,7)
x.numel()

21